# docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo

version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017 #External Internal ports
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
